version: '2.4'

x-limits: &limits
    pids_limit: 1024
    cpu_shares: 256
    mem_limit: 512m
    logging:
        options:
            max-size: 10m
            max-file: '3'

services:
    goldenpage:
        <<: *limits
        build: .
        image: naumachia/goldenpage.actor
        networks:
            default:
                ipv4_address: 172.30.0.7
        restart: unless-stopped        

networks:
    default:
        driver: l2bridge
        ipam:
            driver: static
            config:
                - subnet: 172.30.0.0/28
    naumachia_default:
